---
language: go

go:
  - '1.6'
  - '1.8'
  - '1.9'
  - '1.10'
  - master

before_script:
  - go get -t -v ./...

script:
  - go vet -v ./...
  - go test -v ./...

matrix:
  fast_finish: true
  allow_failures:
    - go: master
